#!/bin/sh

echo "installing node 10.x"
curl -sL https://deb.nodesource.com/setup_10x > ~/node_setup.sh
sudo bash ~/node_setup.sh
sudo apt-get install -y nodejs
node -v

echo "installing fswebcam"
sudo apt-get install -y fswebcam

echo "finished"
